### ISSUE TITLE
curl and java commands not found

### ISSUE THREAD

**Issue by samcarlinone** [rlenferink/docker-minecraft#4]
Trying to run the container, getting the following error
```
/start: line 8: curl: command not found
/start: line 16: java: command not found
```

**Comment by rlenferink** [comment]
Thanks for the notice!

I’ll try to have a look at it tomorrow. Otherwise it will be the beginning of next week.

**Comment by rlenferink** [comment]
I had some time in between and added the curl and jdk requirements. It should run now.

Quick start:
```bash
docker pull rlenferink/minecraft:latest
docker run -d --name=mc -p 25565:25565 rlenferink/minecraft:latest /start
```

Let me know if this solved your problem.
Thanks again!

**Comment by samcarlinone** [comment]
That seems to have fixed it for me. Thanks!
